server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://booking-service.default.svc.cluster.local:8080
          predicates:
            - Path=/booking-service/**
          filters:
            - RewritePath=/booking-service/(?<path>.*), /${path}
         - id: hall-service
          uri: http://hall-service.default.svc.cluster.local:8080
          predicates:
            - Path=/hall-service/**
          filters:
            - RewritePath=/hall-service/(?<path>.*), /${path}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:8080
          predicates:
            - Path=/user-service/**
            - Path=/user/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /${path}
        - id: oauth2-service
          uri: http://user-service.default.svc.cluster.local:8080
          predicates:
            - Path=/oauth2/**
        - id: oauth2-redirect
          uri: http://user-service.default.svc.cluster.local:8080
          predicates:
            - Path=/login/oauth2/code/**
        - id: film-service
          uri: http://film-service.default.svc.cluster.local:8080
          predicates:
            - Path=/film-service/**
          filters:
            - RewritePath=/film-service/(?<path>.*), /${path}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
